function [subject,AIM,dimeSN,dimeFile,startTime,stopTime,bedTime,wakeTime] = importIndex(workbookFile,sheetName,startRow,endRow)
%IMPORTINDEX Import data from a spreadsheet
%   [subject,AIM,dimeSN,dimeFile,startTime,stopTime,bedTime,wakeTime] =
%   IMPORTINDEX(FILE) reads data from the first worksheet in the Microsoft
%   Excel spreadsheet file named FILE and returns the data as column
%   vectors.
%
%   [subject,AIM,dimeSN,dimeFile,startTime,stopTime,bedTime,wakeTime] =
%   IMPORTINDEX(FILE,SHEET) reads from the specified worksheet.
%
%   [subject,AIM,dimeSN,dimeFile,startTime,stopTime,bedTime,wakeTime] =
%   IMPORTINDEX(FILE,SHEET,STARTROW,ENDROW) reads from the specified
%   worksheet for the specified row interval(s). Specify STARTROW and
%   ENDROW as a pair of scalars or vectors of matching size for
%   dis-contiguous row intervals. To read to the end of the file specify an
%   ENDROW of inf.
%
%	Date formatted cells are converted to MATLAB serial date number format
%	(datenum).
%   Non-numeric cells are replaced with: NaN
%
% Example:
%   [subject,AIM,dimeSN,dimeFile,startTime,stopTime,bedTime,wakeTime] =
%   importIndex('index.xlsx','Sheet1',2,28);
%
%   See also XLSREAD.

% Auto-generated by MATLAB on 2013/10/10 10:27:50

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 3
    startRow = 2;
    endRow = 28;
end

%% Import the data, extracting spreadsheet dates in MATLAB serial date number format (datenum)
[~, ~, raw, dateNums] = xlsread(workbookFile, sheetName, sprintf('A%d:H%d',startRow(1),endRow(1)),'' , @convertSpreadsheetDates);
for block=2:length(startRow)
    [~, ~, tmpRawBlock,tmpDateNumBlock] = xlsread(workbookFile, sheetName, sprintf('A%d:H%d',startRow(block),endRow(block)),'' , @convertSpreadsheetDates);
    raw = [raw;tmpRawBlock]; %#ok<AGROW>
    dateNums = [dateNums;tmpDateNumBlock]; %#ok<AGROW>
end
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};
cellVectors = raw(:,4);
raw = raw(:,[1,2,3,5,6,7,8]);
dateNums = dateNums(:,[1,2,3,5,6,7,8]);

%% Replace date strings by MATLAB serial date numbers (datenum)
R = ~cellfun(@isequalwithequalnans,dateNums,raw) & cellfun('isclass',raw,'char'); % Find spreadsheet dates
raw(R) = dateNums(R);

%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),raw); % Find non-numeric cells
raw(R) = {NaN}; % Replace non-numeric cells

%% Create output variable
data = reshape([raw{:}],size(raw));

%% Remove rows missing data (not including missing bedTime or wakeTime)
% Find rows missing data
idx1 = isnan(data(:,1:5));
idx2 = cellfun('isempty',cellVectors);
idx3 = idx1(:,1) | idx1(:,2) | idx1(:,3) | idx1(:,4) | idx1(:,5) | idx2;
% Remove rows missing data
data(idx3,:) = [];
cellVectors(idx3,:) = [];

%% Allocate imported array to column variable names
subject = data(:,1);
AIM = data(:,2);
dimeSN = data(:,3);
dimeFile = cellVectors(:,1);
startTime = data(:,4);
stopTime = data(:,5);
bedTime = mod(data(:,6),1); % Time in fraction of day
wakeTime = mod(data(:,7),1); % Time in fraction of day

%% Replace missing bedTime and wakeTime
idx4 = isnan(bedTime);
bedTime(idx4) = 14/24; % 14:00
idx5 = isnan(wakeTime);
wakeTime(idx5) = 10/24; % 10:00

end

